### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by jsamr**
Add `index.d.ts` :-)

### CODE REVIEW

**Comment by satazor** [comment]
Thanks for the effort in doing the PR but I will have to close it. While it does add the benefit of having typings for typescript users consuming this module, it will add a maintenance burden, specially since this module is not written in typescript.

Again, I’m sorry and hope you understand.

**Comment by jsamr** [comment]
@satazor ; well, I understand the maintenance burden you are consciously avoiding. However your API surface is very thin, and you could ping me on releases to get the job done.

Either that or I'll publish the definitions to definitely typed.

**Comment by satazor** [comment]
Exactly, it’s to avoid the maintenance burden. I know it’s thin but today is typescript, tomorrow is flow, and in the future is something else.

I would publish the definitions to definitively typed. 🙏

**Comment by jsamr** [comment]
@satazor https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39197
Should land soon.

**Comment by jsamr** [comment]
@satazor Please mention me on any API changes and I'll offer a PR in DT.

**Comment by jsamr** [comment]
https://www.npmjs.com/package/@types/proper-url-join

**Pull request closed without merging**
